# Generated by Django 5.0.2 on 2024-02-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0002_team_teammate_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команды', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teammate',
            options={'verbose_name': 'Состав команды', 'verbose_name_plural': 'Состав команды'},
        ),
    ]
